use crate::string::segment::{
    FeatureState::{NA, NEG, POS},
    PhonoSegment,
};

// syl,stress,long,cons,son,cont,delrel,approx,tap,trill,nasal,voi,spgl,congl,lab,round,labdent,cor,ant,dist,strident,lateral,dor,high,low,front,back,tense

// segments that represent common ipa symbols
#[rustfmt::skip]
pub const IPA_BASES: &[(&str, PhonoSegment)] = &[
	("ɒ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,NEG,POS,NA])
	),
	("ɑ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,NEG,POS,NA])
	),
	("ɶ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,POS,NEG,NA])
	),
	("a", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,NEG,NEG,NA])
	),
	("æ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,POS,NEG,NA])
	),
	("ʌ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NEG])
	),
	("ɔ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NEG])
	),
	("o", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,POS])
	),
	("ɤ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,POS])
	),
	("ɘ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,NEG,POS])
	),
	("œ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,POS,NEG,NEG])
	),
	("ə", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,NEG,NEG])
	),
	("e", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,POS,NEG,POS])
	),
	("ɞ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,NEG,NEG])
	),
	("ø", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,POS,NEG,POS])
	),
	("ɛ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,POS,NEG,NEG])
	),
	("ɵ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,NEG,POS])
	),
	("ɯ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,POS])
	),
	("u", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,POS])
	),
	("ʊ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NEG])
	),
	("ɨ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,NEG,POS])
	),
	("ʉ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,NEG,POS])
	),
	("y", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,POS])
	),
	("i", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,POS])
	),
	("ʏ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,NEG])
	),
	("ɪ", PhonoSegment::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,NEG])
	),
	("ɫ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɴ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ʀ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɲ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ʎ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,POS,POS,POS,NEG,POS,NEG,NA])
	),
	("ŋ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ŋ̠", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NA])
	),
	("ʟ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,POS,POS,POS,NEG,NA,NA,NA])
	),
	("ʟ̠", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,POS,POS,POS,NEG,NEG,POS,NA])
	),
	("ɳ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʙ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,POS,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɭ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ɺ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ɻ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɽ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("r", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("n", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("m", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("l", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ɾ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɱ", PhonoSegment::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʔ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ħ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,NEG,POS,NA])
	),
	("ʕ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,NEG,POS,NA])
	),
	("ʁ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("q", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("χ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɢ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɕ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ɟ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ʝ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("c", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ç", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("d͡ʑ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("t͡ɕ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ɣ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ɣ̠", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NA])
	),
	("x", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("k", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ɡ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("g", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ɡ̠", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NA])
	),
	("ʑ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ʈ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɖ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɬ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ʐ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɸ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʂ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʒ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("z", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("v", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("t", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʃ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("s", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("p", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("f", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("d", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("b", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("θ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɮ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ð", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("β", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("d͡ʒ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("d͡z", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("d͡ɮ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("d̠͡ɮ̠", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("t͡ʃ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("t̠͡ɬ̠", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("t͡s", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("t͡ɬ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("t̪͡s̪", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("t̪͡ɬ̪", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("d̪͡z̪", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("d̪͡ɮ̪", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ʈ͡ʂ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɖ͡ʐ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("p͡f", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("b͡v", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("p͡ɸ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("b͡β", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("t̪͡θ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("c͡ç", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ɟ͡ʝ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("k͡x", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("k̠͡x̠", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NA])
	),
	("ɡ͡ɣ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ɡ̠͡ɣ̠", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NA])
	),
	("q͡χ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɢ͡ʁ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɧ", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("k͡p", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ɡ͡b", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("p͡t", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("b͡d", PhonoSegment::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɰ", PhonoSegment::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,POS])
	),
	("ɰ̠", PhonoSegment::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,POS])
	),
	("w", PhonoSegment::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,POS])
	),
	("ɥ", PhonoSegment::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,POS])
	),
	("j", PhonoSegment::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,POS])
	),
	("ɹ", PhonoSegment::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʋ", PhonoSegment::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʍ", PhonoSegment::from_features(
		[NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,POS])
	),
	("ɦ", PhonoSegment::from_features(
		[NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("h", PhonoSegment::from_features(
		[NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	)
];
