use crate::phonology::segment::SegmentFeatures;

use crate::phonology::feature::FeatureState::*;

// syl,long,cons,son,cont,delrel,approx,tap,trill,nasal,voi,spgl,congl,lab,round,labdent,cor,ant,dist,strident,lateral,dor,high,low,front,back,tense

// segments that represent common ipa symbols
#[rustfmt::skip]
pub const IPA_BASES: &[(&str, SegmentFeatures)] = &[
	("ɒ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,NEG,POS,NA])
	),
	("ɑ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,NEG,POS,NA])
	),
	("ɶ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,POS,NEG,NA])
	),
	("a", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,NEG,NEG,NA])
	),
	("æ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,POS,NEG,NA])
	),
	("ʌ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NEG])
	),
	("ɔ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NEG])
	),
	("o", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,POS])
	),
	("ɤ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,POS])
	),
	("ɘ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,NEG,POS])
	),
	("œ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,POS,NEG,NEG])
	),
	("ə", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,NEG,NEG])
	),
	("e", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,POS,NEG,POS])
	),
	("ɞ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,NEG,NEG])
	),
	("ø", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,POS,NEG,POS])
	),
	("ɛ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,POS,NEG,NEG])
	),
	("ɵ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,NEG,POS])
	),
	("ɯ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,POS])
	),
	("u", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,POS])
	),
	("ʊ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NEG])
	),
	("ɨ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,NEG,POS])
	),
	("ʉ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,NEG,POS])
	),
	("y", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,POS])
	),
	("i", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,POS])
	),
	("ʏ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,NEG])
	),
	("ɪ", SegmentFeatures::from_features(
		[POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,NEG])
	),
	("ɫ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɴ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ʀ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɲ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ʎ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,POS,POS,POS,NEG,POS,NEG,NA])
	),
	("ŋ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ŋ̠", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NA])
	),
	("ʟ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,POS,POS,POS,NEG,NA,NA,NA])
	),
	("ʟ̠", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,POS,POS,POS,NEG,NEG,POS,NA])
	),
	("ɳ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʙ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,POS,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɭ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ɺ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ɻ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɽ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("r", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("n", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("m", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("l", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ɾ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,POS,NEG,POS,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɱ", SegmentFeatures::from_features(
		[NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʔ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ħ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,NEG,POS,NA])
	),
	("ʕ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,POS,NEG,POS,NA])
	),
	("ʁ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("q", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("χ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɢ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɕ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ɟ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ʝ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("c", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ç", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("d͡ʑ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("t͡ɕ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ɣ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ɣ̠", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NA])
	),
	("x", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("k", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ɡ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("g", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ɡ̠", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NA])
	),
	("ʑ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ʈ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɖ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɬ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ʐ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɸ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʂ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʒ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("z", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("v", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("t", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʃ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("s", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("p", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("f", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("d", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("b", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("θ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɮ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ð", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("β", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("d͡ʒ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("d͡z", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("d͡ɮ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("d̠͡ɮ̠", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("t͡ʃ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("t̠͡ɬ̠", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("t͡s", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("t͡ɬ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("t̪͡s̪", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("t̪͡ɬ̪", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("d̪͡z̪", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("d̪͡ɮ̪", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,NEG,POS,NEG,NA,NA,NA,NA,NA])
	),
	("ʈ͡ʂ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɖ͡ʐ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("p͡f", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("b͡v", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("p͡ɸ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("b͡β", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("t̪͡θ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,POS,POS,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("c͡ç", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("ɟ͡ʝ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NA])
	),
	("k͡x", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("k̠͡x̠", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NA])
	),
	("ɡ͡ɣ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ɡ̠͡ɣ̠", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,NA])
	),
	("q͡χ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɢ͡ʁ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,NEG,NEG,NEG,POS,NA])
	),
	("ɧ", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("k͡p", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("ɡ͡b", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,NA])
	),
	("p͡t", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("b͡d", SegmentFeatures::from_features(
		[NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,POS,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ɰ", SegmentFeatures::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NA,NA,POS])
	),
	("ɰ̠", SegmentFeatures::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,POS])
	),
	("w", SegmentFeatures::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,POS])
	),
	("ɥ", SegmentFeatures::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,POS])
	),
	("j", SegmentFeatures::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,POS,NEG,POS])
	),
	("ɹ", SegmentFeatures::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,NEG,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʋ", SegmentFeatures::from_features(
		[NEG,NEG,NEG,POS,POS,NA,POS,NEG,NEG,NEG,POS,NEG,NEG,POS,NEG,POS,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("ʍ", SegmentFeatures::from_features(
		[NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,POS,POS,NEG,NEG,NA,NA,NA,NEG,POS,POS,NEG,NEG,POS,POS])
	),
	("ɦ", SegmentFeatures::from_features(
		[NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,POS,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	),
	("h", SegmentFeatures::from_features(
		[NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NEG,POS,NEG,NEG,NEG,NEG,NEG,NA,NA,NA,NEG,NEG,NA,NA,NA,NA,NA])
	)
];
